source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.4'
# Use sqlite3 as the database for Active Record
# gem 'sqlite3'
# gem 'mysql2'
gem 'pg'

# Use Puma as the app server
gem 'puma', '~> 3.7'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
# gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
# gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

gem 'ransack'

# Authentication
gem 'devise'
gem 'devise-i18n'

gem 'omniauth'
# gem 'omniauth-dataporten'
gem 'omniauth-facebook'
gem 'omniauth-github'
gem 'omniauth-google-oauth2'
gem 'omniauth-linkedin-oauth2'

# Bootstrap
# gem 'bootstrap', '4.0.0.beta.2.1'

# Authorization
gem 'pundit'

gem 'sentry-raven'

# Haml power
gem 'haml'
gem 'haml-rails'

gem 'simple_form', '~> 3.5'

# pagination
gem 'kaminari'

# File storage
gem 'carrierwave'
gem 'carrierwave-i18n'

# For validating email addresses
# gem 'valid_email2'

# gem 'sidekiq'
# # Unique jobs in non-enterprise sidekiq :)
# gem 'sidekiq-unique-jobs'

# Delayed job does not work with rails 5.1...

# gem 'delayed_job'
# gem 'delayed_job_active_record'

gem 'slack-ruby-client'

group :development, :test do
  gem 'rspec-rails', '~> 3.7' # , group: [:development, :test]

  gem 'faker'
  # gem 'thin'
  gem 'factory_bot_rails' # , require: false # , group: [:test]

  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # gem 'better_errors'
  # gem 'binding_of_caller'

  # This gem fixes puma issue temporarly
  # gem 'debug-extras'

  # gem 'quiet_assets'

  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  gem 'pry-rails'
  gem 'pry-toys'

  # gem 'guard-bundler', require: false
  # gem 'guard-foreman' # , github: 'leifcr/guard-foreman', require: false

  gem 'guard-livereload', require: false

  # Use Capistrano for deployment
  gem 'capistrano', require: false
  gem 'capistrano-db-tasks', require: false # , git: 'https://github.com/leifcr/capistrano-db-tasks.git', tag: 'v0.4.1'
  gem 'capistrano-delayed_job', require: false
  gem 'capistrano-monit_runit', require: false
  gem 'capistrano-pumaio', require: false
  gem 'capistrano-rails', require: false

end


group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 2.13'
  gem 'database_cleaner'
  gem 'capybara-screenshot'
  gem 'shoulda-matchers'
  gem 'timecop'

  gem 'capybara-selenium'
  gem 'chromedriver-helper'

  # Alternative: change to https://github.com/elgalu/docker-selenium
  # For using real chrome/ff browsers through selenium

  # Coverage
  # gem 'simplecov', require: false
  # gem 'simplecov-rcov', require: false

  # Notificiations sent to growl through gntp
  gem 'ruby_gntp'
end

# Nested sets:
# gem 'awesome_nested_set'

# Ordering various models
gem 'ranked-model'

# Friendly slugged id's
gem 'friendly_id'

# For inlining css on emails (gmail + others remove css styles...)
gem 'inky-rb', require: 'inky'
gem 'premailer-rails'

# Caching in memcached through dalli
# gem 'dalli'

# Connection pooling for dalli/puma, when running multi threaded:
# See https://github.com/petergoldstein/dalli#multithreading-and-rails
# gem 'connection_pool'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
